// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: han-wt32

#include "../ui.h"

void ui_ClockScreen_screen_init(void)
{
    ui_ClockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ClockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ClockScreen, &ui_img_back_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_ClockScreen, &ui_img_back_back_png, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 8);
    lv_obj_set_y(ui_Label14, -4);
    lv_label_set_text(ui_Label14, "Clock");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_star32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblclock2 = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_lblclock2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblclock2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblclock2, -6);
    lv_obj_set_y(ui_lblclock2, -28);
    lv_obj_set_align(ui_lblclock2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblclock2, "00:00");
    lv_obj_set_style_text_color(ui_lblclock2, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblclock2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblclock2, &ui_font_calculator128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnpre3 = lv_btn_create(ui_ClockScreen);
    lv_obj_set_width(ui_btnpre3, 100);
    lv_obj_set_height(ui_btnpre3, 50);
    lv_obj_set_x(ui_btnpre3, -181);
    lv_obj_set_y(ui_btnpre3, 121);
    lv_obj_set_align(ui_btnpre3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnpre3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnpre3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnpre3, lv_color_hex(0x2EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnpre3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnconfirm3 = lv_btn_create(ui_ClockScreen);
    lv_obj_set_width(ui_btnconfirm3, 100);
    lv_obj_set_height(ui_btnconfirm3, 50);
    lv_obj_set_x(ui_btnconfirm3, -63);
    lv_obj_set_y(ui_btnconfirm3, 121);
    lv_obj_set_align(ui_btnconfirm3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnconfirm3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnconfirm3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnconfirm3, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnconfirm3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnpost3 = lv_btn_create(ui_ClockScreen);
    lv_obj_set_width(ui_btnpost3, 100);
    lv_obj_set_height(ui_btnpost3, 50);
    lv_obj_set_x(ui_btnpost3, 60);
    lv_obj_set_y(ui_btnpost3, 122);
    lv_obj_set_align(ui_btnpost3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnpost3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnpost3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnpost3, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnpost3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btndelete3 = lv_btn_create(ui_ClockScreen);
    lv_obj_set_width(ui_btndelete3, 100);
    lv_obj_set_height(ui_btndelete3, 50);
    lv_obj_set_x(ui_btndelete3, 183);
    lv_obj_set_y(ui_btndelete3, 122);
    lv_obj_set_align(ui_btndelete3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btndelete3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btndelete3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btndelete3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btndelete3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -185);
    lv_obj_set_y(ui_Label17, 121);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Home");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -64);
    lv_obj_set_y(ui_Label21, 121);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Stats");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 57);
    lv_obj_set_y(ui_Label24, 122);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Clock");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 183);
    lv_obj_set_y(ui_Label27, 122);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Settings");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHeight2 = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_lblHeight2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHeight2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHeight2, -6);
    lv_obj_set_y(ui_lblHeight2, -96);
    lv_obj_set_align(ui_lblHeight2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHeight2, "000000");
    lv_obj_set_style_text_color(ui_lblHeight2, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHeight2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblHeight2, &ui_font_calculator48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -171);
    lv_obj_set_y(ui_Label37, -54);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "UTC");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -157);
    lv_obj_set_y(ui_Label38, -92);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "Height");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_ClockScreen);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -149);
    lv_obj_set_y(ui_Label40, 36);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "Halving");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barhalving = lv_bar_create(ui_ClockScreen);
    lv_bar_set_value(ui_barhalving, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barhalving, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barhalving, 457);
    lv_obj_set_height(ui_barhalving, 17);
    lv_obj_set_x(ui_barhalving, -2);
    lv_obj_set_y(ui_barhalving, 63);
    lv_obj_set_align(ui_barhalving, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_barhalving, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barhalving, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_barhalving, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_barhalving, lv_color_hex(0xFAFF20), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barhalving, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnpre3, ui_event_btnpre3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnconfirm3, ui_event_btnconfirm3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnpost3, ui_event_btnpost3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btndelete3, ui_event_btndelete3, LV_EVENT_ALL, NULL);

}
