// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: han-wt32

#include "../ui.h"

void ui_StatsScreen_screen_init(void)
{
    ui_StatsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StatsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_StatsScreen, &ui_img_sky_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnconfirm2 = lv_btn_create(ui_StatsScreen);
    lv_obj_set_width(ui_btnconfirm2, 100);
    lv_obj_set_height(ui_btnconfirm2, 50);
    lv_obj_set_x(ui_btnconfirm2, -59);
    lv_obj_set_y(ui_btnconfirm2, 124);
    lv_obj_set_align(ui_btnconfirm2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnconfirm2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnconfirm2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnconfirm2, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnconfirm2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnpost2 = lv_btn_create(ui_StatsScreen);
    lv_obj_set_width(ui_btnpost2, 100);
    lv_obj_set_height(ui_btnpost2, 50);
    lv_obj_set_x(ui_btnpost2, 60);
    lv_obj_set_y(ui_btnpost2, 124);
    lv_obj_set_align(ui_btnpost2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnpost2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnpost2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnpost2, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnpost2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_StatsScreen);
    lv_img_set_src(ui_Image2, &ui_img_1552732429);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image2, -10);
    lv_obj_set_y(ui_Image2, -13);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btndelete2 = lv_btn_create(ui_StatsScreen);
    lv_obj_set_width(ui_btndelete2, 100);
    lv_obj_set_height(ui_btndelete2, 50);
    lv_obj_set_x(ui_btndelete2, 183);
    lv_obj_set_y(ui_btndelete2, 124);
    lv_obj_set_align(ui_btndelete2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btndelete2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btndelete2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btndelete2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btndelete2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnpre2 = lv_btn_create(ui_StatsScreen);
    lv_obj_set_width(ui_btnpre2, 100);
    lv_obj_set_height(ui_btnpre2, 50);
    lv_obj_set_x(ui_btnpre2, -177);
    lv_obj_set_y(ui_btnpre2, 124);
    lv_obj_set_align(ui_btnpre2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnpre2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnpre2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnpre2, lv_color_hex(0x2EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnpre2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -51);
    lv_obj_set_y(ui_Label13, -128);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Stats (To Be Done)");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_star32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -179);
    lv_obj_set_y(ui_Label14, 126);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Pre");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 59);
    lv_obj_set_y(ui_Label16, 126);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Post");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnpost2, ui_event_btnpost2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnpre2, ui_event_btnpre2, LV_EVENT_ALL, NULL);

}
