// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: han-wt32

#include "../ui.h"

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SettingsScreen, &ui_img_back_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_SettingsScreen, &ui_img_back_back_png, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 8);
    lv_obj_set_y(ui_Label15, -4);
    lv_label_set_text(ui_Label15, "Settings");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_star32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnpre4 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_btnpre4, 100);
    lv_obj_set_height(ui_btnpre4, 50);
    lv_obj_set_x(ui_btnpre4, -181);
    lv_obj_set_y(ui_btnpre4, 121);
    lv_obj_set_align(ui_btnpre4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnpre4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnpre4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnpre4, lv_color_hex(0x2EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnpre4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnconfirm4 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_btnconfirm4, 100);
    lv_obj_set_height(ui_btnconfirm4, 50);
    lv_obj_set_x(ui_btnconfirm4, -63);
    lv_obj_set_y(ui_btnconfirm4, 121);
    lv_obj_set_align(ui_btnconfirm4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnconfirm4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnconfirm4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnconfirm4, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnconfirm4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnpost4 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_btnpost4, 100);
    lv_obj_set_height(ui_btnpost4, 50);
    lv_obj_set_x(ui_btnpost4, 60);
    lv_obj_set_y(ui_btnpost4, 122);
    lv_obj_set_align(ui_btnpost4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnpost4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnpost4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnpost4, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnpost4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btndelete4 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_btndelete4, 100);
    lv_obj_set_height(ui_btndelete4, 50);
    lv_obj_set_x(ui_btndelete4, 183);
    lv_obj_set_y(ui_btndelete4, 122);
    lv_obj_set_align(ui_btndelete4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btndelete4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btndelete4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btndelete4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btndelete4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -185);
    lv_obj_set_y(ui_Label19, 121);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Home");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -64);
    lv_obj_set_y(ui_Label22, 121);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Stats");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 57);
    lv_obj_set_y(ui_Label25, 122);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Clock");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 183);
    lv_obj_set_y(ui_Label28, 122);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Settings");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btndelete1 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_btndelete1, 100);
    lv_obj_set_height(ui_btndelete1, 39);
    lv_obj_set_x(ui_btndelete1, 183);
    lv_obj_set_y(ui_btndelete1, -32);
    lv_obj_set_align(ui_btndelete1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btndelete1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btndelete1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btndelete1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btndelete1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 180);
    lv_obj_set_y(ui_Label1, -31);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "RESET");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 343);
    lv_obj_set_height(ui_Container6, 17);
    lv_obj_set_x(ui_Container6, -61);
    lv_obj_set_y(ui_Container6, -47);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container6, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container6, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 464);
    lv_obj_set_height(ui_Container7, 17);
    lv_obj_set_x(ui_Container7, -1);
    lv_obj_set_y(ui_Container7, -18);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container7, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container7, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 464);
    lv_obj_set_height(ui_Container8, 17);
    lv_obj_set_x(ui_Container8, -1);
    lv_obj_set_y(ui_Container8, 12);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container8, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container8, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container8, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -188);
    lv_obj_set_y(ui_Label30, -21);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Address");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -206);
    lv_obj_set_y(ui_Label29, -50);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Pool");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -217);
    lv_obj_set_y(ui_Label31, -78);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "IP");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 343);
    lv_obj_set_height(ui_Container5, 17);
    lv_obj_set_x(ui_Container5, -59);
    lv_obj_set_y(ui_Container5, -75);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container5, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container5, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblIp = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_lblIp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblIp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblIp, 44);
    lv_obj_set_y(ui_lblIp, 71);
    lv_label_set_text(ui_lblIp, "127.0.0.1");
    lv_obj_set_style_text_color(ui_lblIp, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblIp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblIp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPool = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_lblPool, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPool, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPool, 67);
    lv_obj_set_y(ui_lblPool, 99);
    lv_label_set_text(ui_lblPool, "127.0.0.1");
    lv_obj_set_style_text_color(ui_lblPool, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPool, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPool, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblAddress = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_lblAddress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAddress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAddress, 13);
    lv_obj_set_y(ui_lblAddress, 158);
    lv_label_set_text(ui_lblAddress, "127.0.0.1");
    lv_obj_set_style_text_color(ui_lblAddress, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblAddress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblAddress, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblversion2 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_lblversion2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblversion2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblversion2, 93);
    lv_obj_set_y(ui_lblversion2, 220);
    lv_label_set_text(ui_lblversion2, "version ");
    lv_obj_set_style_text_color(ui_lblversion2, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblversion2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblversion2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_lblversion2, &ui_img_back_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -192);
    lv_obj_set_y(ui_Label42, 68);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "Version");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnpre4, ui_event_btnpre4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnconfirm4, ui_event_btnconfirm4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnpost4, ui_event_btnpost4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btndelete4, ui_event_btndelete4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btndelete1, ui_event_btndelete1, LV_EVENT_ALL, NULL);

}
