// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: han-wt32

#include "../ui.h"

void ui_StatsScreen_screen_init(void)
{
    ui_StatsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StatsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_StatsScreen, &ui_img_back_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_StatsScreen, &ui_img_back_back_png, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 8);
    lv_obj_set_y(ui_Label2, -4);
    lv_label_set_text(ui_Label2, "Statistics");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_star32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnpre2 = lv_btn_create(ui_StatsScreen);
    lv_obj_set_width(ui_btnpre2, 100);
    lv_obj_set_height(ui_btnpre2, 50);
    lv_obj_set_x(ui_btnpre2, -181);
    lv_obj_set_y(ui_btnpre2, 121);
    lv_obj_set_align(ui_btnpre2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnpre2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnpre2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnpre2, lv_color_hex(0x2EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnpre2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnconfirm2 = lv_btn_create(ui_StatsScreen);
    lv_obj_set_width(ui_btnconfirm2, 100);
    lv_obj_set_height(ui_btnconfirm2, 50);
    lv_obj_set_x(ui_btnconfirm2, -63);
    lv_obj_set_y(ui_btnconfirm2, 121);
    lv_obj_set_align(ui_btnconfirm2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnconfirm2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnconfirm2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnconfirm2, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnconfirm2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnpost2 = lv_btn_create(ui_StatsScreen);
    lv_obj_set_width(ui_btnpost2, 100);
    lv_obj_set_height(ui_btnpost2, 50);
    lv_obj_set_x(ui_btnpost2, 60);
    lv_obj_set_y(ui_btnpost2, 122);
    lv_obj_set_align(ui_btnpost2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnpost2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnpost2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnpost2, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnpost2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btndelete2 = lv_btn_create(ui_StatsScreen);
    lv_obj_set_width(ui_btndelete2, 100);
    lv_obj_set_height(ui_btndelete2, 50);
    lv_obj_set_x(ui_btndelete2, 183);
    lv_obj_set_y(ui_btndelete2, 122);
    lv_obj_set_align(ui_btndelete2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btndelete2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btndelete2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btndelete2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btndelete2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -185);
    lv_obj_set_y(ui_Label16, 121);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Home");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -64);
    lv_obj_set_y(ui_Label20, 121);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Stats");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 57);
    lv_obj_set_y(ui_Label23, 122);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Clock");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 183);
    lv_obj_set_y(ui_Label26, 122);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Settings");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_StatsScreen);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 464);
    lv_obj_set_height(ui_Container10, 17);
    lv_obj_set_x(ui_Container10, -1);
    lv_obj_set_y(ui_Container10, -47);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container10, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container10, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container10, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_StatsScreen);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 464);
    lv_obj_set_height(ui_Container11, 17);
    lv_obj_set_x(ui_Container11, -1);
    lv_obj_set_y(ui_Container11, -18);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container11, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container11, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container11, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_StatsScreen);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 464);
    lv_obj_set_height(ui_Container12, 17);
    lv_obj_set_x(ui_Container12, -1);
    lv_obj_set_y(ui_Container12, 12);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container12, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container12, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container12, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_StatsScreen);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 464);
    lv_obj_set_height(ui_Container9, 17);
    lv_obj_set_x(ui_Container9, -1);
    lv_obj_set_y(ui_Container9, 43);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container9, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container9, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container9, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_StatsScreen);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 464);
    lv_obj_set_height(ui_Container13, 17);
    lv_obj_set_x(ui_Container13, -1);
    lv_obj_set_y(ui_Container13, 72);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container13, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container13, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container13, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -81);
    lv_obj_set_y(ui_Label34, -51);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "Global hashrate                 EH/s");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -199);
    lv_obj_set_y(ui_Label35, -91);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Price");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPrice = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_lblPrice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPrice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPrice, 103);
    lv_obj_set_y(ui_lblPrice, 42);
    lv_label_set_text(ui_lblPrice, "0");
    lv_obj_set_style_text_color(ui_lblPrice, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPrice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPrice, &ui_font_calculator48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGlobalHashrate = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_lblGlobalHashrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGlobalHashrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGlobalHashrate, 187);
    lv_obj_set_y(ui_lblGlobalHashrate, 88);
    lv_label_set_text(ui_lblGlobalHashrate, "0000");
    lv_obj_set_style_text_color(ui_lblGlobalHashrate, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblGlobalHashrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblGlobalHashrate, &ui_font_calculator32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDifficulty = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_lblDifficulty, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDifficulty, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDifficulty, 118);
    lv_obj_set_y(ui_lblDifficulty, 118);
    lv_label_set_text(ui_lblDifficulty, "0");
    lv_obj_set_style_text_color(ui_lblDifficulty, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDifficulty, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDifficulty, &ui_font_calculator32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -181);
    lv_obj_set_y(ui_Label32, -21);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Difficulty");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -152);
    lv_obj_set_y(ui_Label33, 9);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "My pool cluster");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 63);
    lv_obj_set_y(ui_Label36, 9);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Workers");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -157);
    lv_obj_set_y(ui_Label39, 39);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Total hashrate");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, -159);
    lv_obj_set_y(ui_Label41, 69);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Max difficulty");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWorkers = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_lblWorkers, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWorkers, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWorkers, 357);
    lv_obj_set_y(ui_lblWorkers, 148);
    lv_label_set_text(ui_lblWorkers, "0");
    lv_obj_set_style_text_color(ui_lblWorkers, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWorkers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWorkers, &ui_font_calculator32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTotHashrate = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_lblTotHashrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTotHashrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTotHashrate, 189);
    lv_obj_set_y(ui_lblTotHashrate, 179);
    lv_label_set_text(ui_lblTotHashrate, "0");
    lv_obj_set_style_text_color(ui_lblTotHashrate, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTotHashrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTotHashrate, &ui_font_calculator32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMaxDifficulty = lv_label_create(ui_StatsScreen);
    lv_obj_set_width(ui_lblMaxDifficulty, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMaxDifficulty, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMaxDifficulty, 189);
    lv_obj_set_y(ui_lblMaxDifficulty, 208);
    lv_label_set_text(ui_lblMaxDifficulty, "0");
    lv_obj_set_style_text_color(ui_lblMaxDifficulty, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMaxDifficulty, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMaxDifficulty, &ui_font_calculator32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnpre2, ui_event_btnpre2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnconfirm2, ui_event_btnconfirm2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnpost2, ui_event_btnpost2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btndelete2, ui_event_btndelete2, LV_EVENT_ALL, NULL);

}
