// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: han-wt32

#include "../ui.h"

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SplashScreen, &ui_img_back_splash_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblpassword = lv_label_create(ui_SplashScreen);
    lv_obj_set_width(ui_lblpassword, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblpassword, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblpassword, 137);
    lv_obj_set_y(ui_lblpassword, 283);
    lv_label_set_text(ui_lblpassword, "password");
    lv_obj_set_style_text_color(ui_lblpassword, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblpassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblpassword, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblssid = lv_label_create(ui_SplashScreen);
    lv_obj_set_width(ui_lblssid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblssid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblssid, 78);
    lv_obj_set_y(ui_lblssid, 247);
    lv_label_set_text(ui_lblssid, "ssid");
    lv_obj_set_style_text_color(ui_lblssid, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblssid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblssid, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblversion = lv_label_create(ui_SplashScreen);
    lv_obj_set_width(ui_lblversion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblversion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblversion, 279);
    lv_obj_set_y(ui_lblversion, 280);
    lv_label_set_text(ui_lblversion, "version ");
    lv_obj_set_style_text_color(ui_lblversion, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblversion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblversion, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_lblversion, &ui_img_back_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);


}
