#ifndef _NERD_MINER_V2_H
#define _NERD_MINER_V2_H

#define PIN_BUTTON_1 0
#define PIN_BUTTON_2 14
#define PIN_ENABLE5V 15

#define T_DISPLAY

#define NERD_NOS_GPIO_TX (GPIO_NUM_17)
#define NERD_NOS_GPIO_RX (GPIO_NUM_18)
#define NERD_NOS_GPIO_RST (GPIO_NUM_12)
#define NERD_NOS_GPIO_PEN (GPIO_NUM_13)
#define NERD_NOS_GPIO_TMP (GPIO_NUM_2)

#endif