// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: han-wt32

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void reset_configuration_event(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
